//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seds.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public Certificate()
        {
            this.Students = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public string CertificateNumber { get; set; }
        public int TypeId { get; set; }
        public System.DateTime GraduationDate { get; set; }
    
        public virtual CertificateType CertificateType { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
