//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seds.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseGroup
    {
        public CourseGroup()
        {
            this.Studies = new HashSet<Study>();
            this.OrganizationalUnits = new HashSet<OrganizationalUnit>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string TitleName { get; set; }
    
        public virtual ICollection<Study> Studies { get; set; }
        public virtual ICollection<OrganizationalUnit> OrganizationalUnits { get; set; }
    }
}
