//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seds.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationalUnit
    {
        public OrganizationalUnit()
        {
            this.CourseGroups = new HashSet<CourseGroup>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string TitleName { get; set; }
        public string IdIsvu { get; set; }
    
        public virtual ICollection<CourseGroup> CourseGroups { get; set; }
    }
}
