//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seds.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student_Studies
    {
        public int StudentId { get; set; }
        public int StudyId { get; set; }
        public System.DateTime EnrollmentYear { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Study Study { get; set; }
    }
}
