//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seds.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Student_Studies = new HashSet<Student_Studies>();
            this.Certificates = new HashSet<Certificate>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string BirthLastName { get; set; }
        public int Gender { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string JMBG { get; set; }
        public string OIB { get; set; }
        public int UniqueNumber { get; set; }
        public Nullable<decimal> AverageRating { get; set; }
        public Nullable<decimal> AverageGroup1 { get; set; }
        public Nullable<decimal> AverageGroup2 { get; set; }
        public Nullable<bool> Verified { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string ImagePath { get; set; }
        public string Note { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Student_Studies> Student_Studies { get; set; }
        public virtual ICollection<Certificate> Certificates { get; set; }
    }
}
