//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seds.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyType
    {
        public StudyType()
        {
            this.Studies = new HashSet<Study>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Study> Studies { get; set; }
    }
}
