//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Seds.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Study
    {
        public Study()
        {
            this.Student_Studies = new HashSet<Student_Studies>();
        }
    
        public int Id { get; set; }
        public int CourseGroupId { get; set; }
        public string Title { get; set; }
        public int Duration { get; set; }
        public int ECTS { get; set; }
        public int TypeId { get; set; }
    
        public virtual CourseGroup CourseGroup { get; set; }
        public virtual ICollection<Student_Studies> Student_Studies { get; set; }
        public virtual StudyType StudyType { get; set; }
    }
}
